### ISSUE TITLE
oper: config_load should handle dependencies

### ISSUE THREAD

**Issue by Ali-aqrabawi** [okda-networks/iproute2-sysrepo#84]
libyang[0]: Invalid union value "br0" - no matching subtype found:
    libyang 2 - leafref, version 1: Invalid leafref value "br0" - no target instance "/iplink:links/iplink:link/iplink:name" with the same value.
    libyang 2 - leafref, version 1: Invalid leafref value "br0" - no target instance "/iplink:links/iplink:bridge/iplink:name" with the same value.
 (path: Data location "/iproute2-ip-link:links/link[name='br-slave']/master".)
load_linux_running_config: Error by sr_apply_changes: Validation failed.

**Comment by adaraiseh** [comment]
Fixed
